# Clean and wrangle data

## Setup

```{r}
library(dplyr)
library(tidyr)
library(readr)
```

## Source data

### Read data

```{r}
#| label: read_data
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
colnames(catch_original)
head(catch_original)
summary(catch_original)
glimpse(catch_original)
```

## Clean and reshape data

### Select data of interest
 
 ```{r}
 catch_data <- catch_original %>%
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
 ```

### Fix character issue

 ```{r}
 catch_clean <- catch_data %>%
    mutate(
        Chinook = if_else(
            Chinook == "I",
            "1",
            Chinook),
        Chinook = as.numeric(Chinook))
    
 ```


### Go from wide to long

 ```{r}
 catch_long <- catch_clean %>%
    pivot_longer(
        cols = -c(Region, Year),
        names_to = "species",
        values_to = "catch_thousands"
    )
 
 ```

### Go from long back to wide

```{r}
catch_wide <- catch_long %>%
    pivot_wider(
        names_from = species,
        values_from = catch_thousands,
        values_fill = 0
    )
head(catch_wide)
```

### Convert catch to individual fish counts (not thousands)

```{r}
catch_long <- catch_long %>%
    mutate(catch = catch_thousands * 1000) %>%
    select(-catch_thousands)
head(catch_long)
```

### Calculate mean catch by region

```{r}
mean_region <- catch_long %>%
    group_by(Region) %>%
    summarize(mean_catch = mean(catch, na.rm = TRUE), .groups = "drop") %>%
    arrange(desc(mean_catch))
    
head(mean_region)
```

### Demonstrate filter

```{r}
sse_catch <- catch_long %>%
    filter(Region == "COP")

head(sse_catch)
```

## Experiment with separate and unite

```{r}
sites_df <- data.frame(site = c("HAW-101", "HAW-103", "OAH-320", "OAH-219", "MAU-039"))
sites_df %>%
    separate_wider_delim(
        cols=site,
        delim = "-",
        names = c("island", "site_number"),
        cols_remove = FALSE)
```


```{r}
#| label: unite
dates_df <- data.frame(
    year  = rep(x = "1930", times = 3),
    month = rep(x = "12",   times = 3),
    day   = 14:16)

# Check that
dates_df %>%
    unite(
        col = date,
        year, month, day,
        sep = "-",
        remove = FALSE
    )
```
