---
title: "Introduction to Quarto"
format: html
editor: visual
---

## Introduction

### About the data

This is a dataset about...

### Setup

```{r}
library(readr)
library(here)
```

### Read in data

```{r}
bg_chem <- read_csv(here::here("data/BGchem2008data.csv"))
```

## Analysis

```{r}
## Prints the column names of my data frame
colnames(bg_chem)

## General structure of the data frame - shows class of each column
str(bg_chem)

## First 6 lines of the data frame
head(bg_chem)

## Summary of each column of data
summary(bg_chem)

## Prints unique values in a column (in this case Date)
unique(bg_chem$Date)
```

### Calculate summary statistics

```{r}
nitrate <- mean(bg_chem$NO3)
nitrite <- mean(bg_chem$NO2)
amm <- mean(bg_chem$NH4)
phos <- mean(bg_chem$P)
```

### Calculate mean Redfield ratio

```{r}
ratio <- (nitrate + nitrite + amm)/phos
```

### Plot Redfield ratio

```{r}
plot(bg_chem$P, bg_chem$NO2 + bg_chem$NO3 + bg_chem$NH4)
```

## Conclusion

Clearly something amazing is happening here!
